### ISSUE TITLE
没有覆盖"#cookie帮助"这条指令

### ISSUE THREAD

**Issue by familior** [SmallK111407/expand-plugin#2]
如图，“sk帮助”、“ck帮助”、“stoken帮助”都被覆盖了，但还有“cookie帮助”没被覆盖。有些群友又跑去手动绑cookie了
![截图_20230228232933](https://user-images.githubusercontent.com/84607943/221900107-12c3b7a5-6c08-4069-b30a-16611a220ace.png)

**Comment by familior** [comment]
在锅巴页面中看到改cookie帮助的地方了

**Comment by SmallK111407** [comment]
已修复无覆盖问题
